### ISSUE TITLE
Is there an offline version for local development?

### ISSUE THREAD

**Issue by karlo-humanmanaged** [vercel/edge-config#94]

**Comment by dferber90** [comment]
Unfortunately we don't have support for working offline at the moment. 

However one way to do this yourself would be to:
- create your own client which internally forwards calls to `@vercel/edge-config` if you want to work online
- set up an environment variable like `OFFLINE=1`
- make your own client check whether the env var if set
- if it is set, return values from a local json file instead

Note that you'd need to import the JSON file directly into your code as reading the file system is not possible from the edge runtime. This might end up in your production bundle if you are not careful though. Another alternative would be to start a local server during development and have your custom client fetch form there instead.

It's a bit manual but it should get you there most of the way.

I'm curious about your use case for working offline. Is it because you are traveling and don't have wifi?

_I'll close this issue for now as we have offline support on the roadmap anyhow. But it will likely be a bit until we get around to it._

**Comment by karlo-humanmanaged** [comment]
Hi, thanks for the reply. Not only that a lot of us are on the road most of the time, we also need some flexibility around keys that would have different values depending on the task we're working on during local development e.g. api endpoints, auth audiences, etc

**Comment by dferber90** [comment]
#166 should help here. Once that lands it will allow supplying your own custom connection string. That way you can run a custom edge config server while working offline during development.
